### ISSUE TITLE
Disposing of an unassignable hit

### ISSUE THREAD

**Issue by EvanBurchard** [ryantate/rturk#1]
When I create a hit, and the task is accepted by the turker, but not yet completed by him/her, it seems that I am in a limbo where I cannot expire! or dispose! of it.

Is this the desired behavior?  Maybe it makes sense for most cases, but I feel like it runs the risk of me having hits sitting around that I can't get rid of.

**Comment by mdp** [comment]
This is a rule enforced by Amazon. You can give a HIT a time to be completed, LifetimeInSeconds, and when it's accepted they have that time to complete it.

If they don't complete it, it will go back into the pool where you can expire it.

**Comment by EvanBurchard** [comment]
Ok.  That makes sense.

Thanks.
