### ISSUE TITLE
Use HTTPS to make requests

### ISSUE THREAD

**Issue by mdp** [ryantate/rturk#12]
Amazon will be deprecating HTTP calls in January 2012. RTurk needs to change to HTTPS calls. I'm putting this here so I don't forget

**Comment by hamin** [comment]
@mdp any chance you can do a version bump with this in it? I have a production app and I would rather not specify the git repo in Gemfile and use a versioned gem instead

**Comment by mdp** [comment]
I bumped it to 2.5.0 back in november and published. I chose to bump it a minor revision since HTTPS is likely to break installs behind a proxy or firewall.

Sadly the publish date on Rubygems says June 3rd, due to a mistake in the gemspec. I corrected this in 2.5.2
