### ISSUE TITLE
Additional HIT details

### ISSUE THREAD

**Issue by sbowman** [ryantate/rturk#16]
It would be nice if when getting details about a HIT you would parse the external question and qualifications.  It comes back with the XML, but it doesn't appear that it's being parsed into the Rturk::Hit adapter.

**Comment by zachhale** [comment]
We'll take a pull request if you've got one! Please fork and add specs
then I'll review your changes. :)

On Jan 18, 2012, at 12:32 PM, Sean Bowman
reply@reply.github.com
wrote:
