### ISSUE TITLE
Allow more than 100 hits to be traversed

### ISSUE THREAD

**Issue by jeremylightsmith** [ryantate/rturk#19]
No time to do this right and fork this, but here's a monkey patch that hopefully will make it's way into main.

```
module RTurk
  class Hit
    def self.each(page_number = 1, &block)
      result = RTurk::SearchHITs.create(page_number:page_number, page_size:100)
      total_num_results = result.xpath("//TotalNumResults").text.to_i
      result.hits.map do |hit|
        yield new(hit.id, hit)
      end
      each(page_number + 1, &block) if total_num_results > page_number * 100
    end
  end
end
```

**Comment by falnor** [comment]
Have these changes been merged in?

**Comment by mdp** [comment]
Nope, I haven't had a chance to write this with the proper test coverage. Jeremy has provided an excellent starting point if anyone wants to jump in and fix it.

**Comment by bluemont** [comment]
This would be very helpful! I'm having trouble with rturk at the moment -- I'm not the person to fix, at least not right now.

**Comment by mdp** [comment]
I'm pretty swamped, but I'll see what I can do tonight.

Also, just to be clear, this is only a limitation on the 'Hit' helper, you can always just make the request directly on GetReviewableHITS with the page_number option set

https://github.com/mdp/rturk/blob/master/lib/rturk/operations/get_reviewable_hits.rb

**Comment by mdp** [comment]
Since this can be worked around pretty easily with GetReviewableHITS directly, I'm going to close it until someone submits a pull request.
