### ISSUE TITLE
Why would the API and Web UI be out of sync?

### ISSUE THREAD

**Issue by bluemont** [ryantate/rturk#29]
http://stackoverflow.com/questions/13277775/why-would-the-amazon-mechanical-turk-web-interface-be-out-of-sync-with-the-api

Any ideas?

**Comment by mdp** [comment]
Do they ever get in sync after a period of time? Also, if you query again using the API, do the reflect the changes you made?

**Comment by bluemont** [comment]
I got a response from an AWS representative on the AWS forum saying this was a "known limitation".

**Comment by mdp** [comment]
Cool, I'll close the issue since it's on their end. Thanks
