### ISSUE TITLE
CreateHIT generate this exception AWS.MechanicalTurk.PermissionDenied

### ISSUE THREAD

**Issue by bilalbash** [ryantate/rturk#33]
RTurk::InvalidRequest: AWS.MechanicalTurk.PermissionDenied: 
This user is not authorized to perform the requested operation.

**Comment by mdp** [comment]
This is probably a permissions error on the AWS credentials being used. Can you check to see if the user has access to Mechanical Turk. I don't think IAM keys are allowed to use Mechanical Turk from what I can tell

**Comment by bilalbash** [comment]
solved: my access id was right but secret key was wrong but do exist on mechanical Turk account under some other heading.. so i followed this link to get actual key and secret pair 
http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkGettingStartedGuide/SetUp.html
