### ISSUE TITLE
Allow more than 100 assignments to be returned

### ISSUE THREAD

**Issue by nbuggia** [ryantate/rturk#37]
I'm having a difficult time retrieving more than 100 assignments from any specific HIT. I wonder if this is a similar issue as #19? 

Essentially, I'm always returned page 1 of results, no matter which page I request.

```
a1 = RTurk::GetAssignmentsForHIT(hit_id: 'HIT_ID', page_size: 10, page: 1)
a2 = RTurk::GetAssignmentsForHIT(hit_id: 'HIT_ID', page_size: 10, page: 2)

# a1 == a2
```

Also, RTurk::HIT.assignments will only allow you to iterate through the first 100 results.

```
hit = RTurk::Hit.find HIT_ID
hit.assignments.each do |a|
  process_assignment a
end
```

It never makes it past 100 assignments

Any help would be greatly appreciated!

**Comment by mdp** [comment]
It looks like it's named `page_number`

https://github.com/mdp/rturk/blob/master/lib/rturk/operations/get_assignments_for_hit.rb

Let me know if that doesn't work and I'll take a look at it.

**Comment by mdp** [comment]
As for the second issue, iteration helpers, this is a known issue and unfortunately I just haven't had the time to jump on it at fix it.

**Comment by nbuggia** [comment]
Thank you, I looked back through the code and documentation and I have no excuse why I used `page` instead of `page_number`. Thank you very much for saving me from myself.

Here's some simple code for iterating through all assignments, may it redeem me at least a little ;)

```
def iterate_through_all_assignments 
  page = 1
  loop do
    results = RTurk::GetAssignmentsForHIT hit_id: 'HIT_ID', page_size: 100, page_number: page
    break if results.num_results == 0

    results.assignments.each do |a| 
      # Do something with your assignment object 'a'
    end

    page += 1
  end
end
```
