### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by mdp** [ryantate/rturk#40]
I've not actively used RTurk since early 2010, so I doubt I'm the best person to keep maintaining this gem. 

If anyone wants to volunteer for the role, I only ask a couple things:
- You currently use the RTurk gem
- You have a decent level of experience maintaining a Ruby gem (Tests!)

All this could be yours :smile: Just let me know!

**Comment by mdp** [comment]
Closing, transferring to Ryan Tate

**Comment by ryantate** [comment]
Just wanted to say I'll do my best to stay on top of issues and pull requests. There is an outstanding (and perfectly reasonable) request for non-global login credentials, but I can't give any estimate of when this might done or make any optimistic noises until I've had more time to dig into the existing code, think on it, beg advice from Mark over beer,  etc.

Beyond bugs and login, the plan is to work steadily on improving the docs and on building out the high-level adapter functionality.

I also wanted to thank Mark for taking time to answer questions and give advice on rturk earlier this month, and for agreeing to continue to help with maintenance. And of course for making rturk! Without which there would be no Turkee, no typingpool,  or any ruby solution for mturk. I look forward to being a conduit for rturk's many awesome contributors.

**Comment by cantino** [comment]
Thanks to you both for your hard work on this super-useful project!

**Comment by ukd1** [comment]
@ryantate if you ever need a hand, we use rturk extensively and love to work on open source stuff.

**Comment by ryantate** [comment]
@ukd1 Thanks much Russell, I may indeed reach out, and feel free to jump in whenever :)

**Comment by ukd1** [comment]
@ryantate :+1:
