### ISSUE TITLE
Newly created HITs (throught rturk) not appearing in RTurk::Hit.all

### ISSUE THREAD

**Issue by messutied** [ryantate/rturk#43]
I also tried with `RTurk::SearchHITs` and I get the same, Im sure the HITs are getting created because I can see them in the Amazon requester admin page.

If any one have any ideas of what could be causing this I would really appreciate it.

**Comment by eggie5** [comment]
Sometimes I've noticed there is a short propagation delay when using the API -- especially on sandbox.

**Comment by messutied** [comment]
Its been almost 24 hours since I created the HITs... Im guessing that the only possible explanation though

**Comment by ryantate** [comment]
24 hours would be quite a delay! I assume you're using sandbox for both (or
neither) creation and reads?

On Nov 12, 2013, at 8:02 AM, Eduardo Messuti notifications@github.com
wrote:

Its been almost 24 hours since I created the HITs... Im guessing that the
only possible explanation though

—
Reply to this email directly or view it on
GitHubhttps://github.com/ryantate/rturk/issues/43#issuecomment-28305727
.

**Comment by messutied** [comment]
Yes sandbox on both read and write, I've double checked... I just realized Im getting exactly 100 HITs from rturk, while in Amazon requester admin there are like 130
`RTurk::Hit.all.size` => 100

Is there any kind of pagination enabled by default in `RTurk::Hit.all`?

**Comment by ryantate** [comment]
No, and RTurk::Hit.all is a just a thin wrapper around RTurk::SearchHITs.create.

The RTurk::Hit adapter doesn't have a convenience method to go past the first 100 HITs, the workaround has traditionally been to pass a page number to RTurk::SearchHITs.create(:page_number => page_number). Per Issue #19 https://github.com/ryantate/rturk/issues/19#issuecomment-10165105

For reviewable HITs, another workaround is to similarly call GetReviewableHITs with a page_number param (see @mdp's reply in the issue above). In the case of a brand new HIT, RTurk::Hit.all_reviewable is often effective as well, assuming it is brand new (and thus still reviewable).

Apologies for not mentioning this in my initial reply; I knew @mdp had touched Issue #19 recently but couldn't remember the outcome. Documenting this shortcoming and then eventually fixing is a priority for me, though no promises on how soon; you should use one of the above workarounds for now.

**Comment by messutied** [comment]
Thanks a lot for the support @ryantate! I'll use one of them
