### ISSUE TITLE
X-Frame-Options from MTurk stopping the submit frame from loading

### ISSUE THREAD

**Issue by onweapps** [ryantate/rturk#49]
I am using RTurk in a rails 4 app, trying to send custom HITs to the requestersanbox. It seems that the response from the form submission cannot be displayed in an iframe because of the response header 'X-Frame-Options'. I ran into the same console error when trying to get my hit to display - but since the hit was hosted server side it was easy to change the header. How do I stop mturk from sending this form header, or is it something I need to do server side?

here is the error
Refused to display 'https://workersandbox.mturk.com/mturk/externalSubmit' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

Really sorry if this is not an issue for this gem!

**Comment by mdp** [comment]
This is mostly likely an issue with Rails 4 sending the X-Frame-Options header. I've not worked with Rails 4 much, but you should be able to turn it off - http://stackoverflow.com/questions/16561066/ruby-on-rails-4-app-not-works-in-iframe

Reopen this issue if that's not the case.
