### ISSUE TITLE
Hit.AssignmentDurationInSeconds

### ISSUE THREAD

**Issue by jclemenson** [ryantate/rturk#7]
Is there support for setting the AssignmentDurationInSeconds?

**Comment by dbalatero** [comment]
Yes, see the source for Hit. Or grep code base for that parameter.

David

**Comment by jclemenson** [comment]
Ah now I see it. I had been searching the codebase for assignment_duration... Thanks! For anyone else looking, the setter is hit.duration=

**Comment by jclemenson** [comment]
closing, non issue.
