### ISSUE TITLE
RequiredToPreview cannot be set to false

### ISSUE THREAD

**Issue by gvelez17** [ryantate/rturk#9]
In qualification_builder.rb, need

43a44,47

> ```
>     if opts.has_key?(:required_to_preview)
>       qualifier[:RequiredToPreview] = opts[:required_to_preview]
>     end
> ```
> 
> 57c61
> ## <       params["RequiredToPreview"] = qualifier[:RequiredToPreview] || 'true'
> 
> ```
>   params["RequiredToPreview"] = qualifier.has_key?(:RequiredToPreview) ? qualifier[:RequiredToPreview] : 'true'
> ```

also the comments about how to add a qualification requirement seemed a little misleading to me.  Maybe you want to make more flexible now for custom requirement types?  I modified the comments as follows in qualifications_builder.rb

20,21c20,21
<     # Needs a type name(you can reference this later)
## <     # and the operation as a hash: ':gt => 85'

> ```
> # Needs a type name (you can reference this later) or your custom type ID
> # and the operation as a hash: ':gt => 85' ; NOTE, though the first key of the hash is special and must be the comparator
> ```
> 
> 23c23
> ## <     # qualifications.add('EnglishSkillsRequirement', :gt => 66, :type_id => '1234567890123456789ABC')
> 
> ```
> # qualifications.add('1234567890123456789ABC', :gt => 66, :require_to_preview => false ) 
> ```

**Comment by gvelez17** [comment]
ouch!  I'm surprised that github doesn't accept diff output in the issues...

**Comment by mdp** [comment]
Hey, can I get you to issue this as a pull request, or alternately you could just email me the diff to mark@markpercival.us and I'll get it in the next revision of the gem.

**Comment by mdp** [comment]
fixed in 2.4.0. Thanks for finding this.
